# Generated by Django 5.2.1 on 2025-06-02 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='owner',
            new_name='owner_id',
        ),
    ]
